name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13.4
      with:
        lein: 2.10.0                  # Leiningen
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test

    - name: Import GPG key
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        echo "trusted-key ${{ secrets.GPG_KEY_ID }}" >> ~/.gnupg/gpg.conf

    - name: Configure GPG for non-interactive use
      run: |
        echo "use-agent" >> ~/.gnupg/gpg.conf
        echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
        echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
        echo "batch" >> ~/.gnupg/gpg.conf
        echo "no-tty" >> ~/.gnupg/gpg.conf
        gpg-connect-agent reloadagent /bye
        # Test GPG signing
        echo "test" | gpg --clearsign --batch --yes --passphrase-fd 0 <<< "${{ secrets.GPG_PASSPHRASE }}"

    - name: Deploy to GitHub Packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: lein deploy github
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        LEIN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_AGENT_INFO: ""
        GPG_TTY: ""
